apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-ngc
spec:
  containers:
  - name: tf
    image: nvcr.io/nvidia/tensorflow:23.03-tf1-py3
    command: [ "jupyter-lab" ]
      #    args: [ "while true; do sleep 30; done;" ]
